### ISSUE TITLE
Complete sequelize config missing from repo

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/dio-service#13]
I believe that _config/config.json_ should be in the repo - correct me if I am wrong.

Running `sequelize init` probably doesn't need to be necessary for new devs.
The config file should have env vars replacing the username, password, etc for each env.

**Comment by ybakos** [comment]
See leehankyeol's coment here: https://github.com/sequelize/cli/issues/77#issuecomment-68299495

**Comment by JWTappert** [comment]
Okay, sweet I'll fix it. I thought that maybe since it was config it should be untracked.

**Comment by ybakos** [comment]
@JWTappert Tracked but with Process.env calls instead of actual config values.
Use a "dot env" lib and .env file, npm has one.

**Comment by JWTappert** [comment]
yup, already using dotenv, I'll swap out the values
