### ISSUE TITLE
.sample-env should not have vars for all three envs

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/dio-service#23]
The config is the config. The _values_ are what changes. The app should only care about one environment variable: the `DB_CONN_URL`. The _value_ of this env var is what changes per environment. With three different env vars, you litter the codebase with if/else statements. "If I am in production, use PROD_VAR, else if I am in test use TEST_VAR, else if..."

@JWTappert I've seen this before in your work and so I want to be sure you understand the role of environment variables and how to properly use them in an app. There should always be just one environment variable for a particular config item, such as the db connection url. The application always refers to that one environment variable. In dev, we have a certain _value_ for that env var that we set typically via a .env or an actual explicit environment variable. In test, the test script should set the value of that same env var to whatever the value should be in the test env. In production, we set the environment variable explicitly, and the app does not use the values in a .env file.

Let me know if you do not understand this.

**Comment by JWTappert** [comment]
I understand. All of the examples I've seen use different variables for each environment, including the one I followed for this setup, so that is why I've added it.
