### ISSUE TITLE
Standardize naming

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/dio-service#9]
@JWTappert Let's standardize the naming to be **diO** since it is **di**ssolved **O**xygen. What do you think?

/cc @MakeilaLundy

**Comment by ybakos** [comment]
This affects the README.

**Comment by MakeilaLundy** [comment]
I agree ☝️ DiO looks better to me

**Comment by ybakos** [comment]
@JWTappert @MakeilaLundy You win. 😄
